---
# Playbook to completely reset/cleanup Kafka installation including user/group
# WARNING: This will completely remove Kafka, all its data, and the kafka user!
#
# Usage:
#   ansible-playbook -i inventory reset-kafka-with-user.yml
#
# To skip confirmation prompt:
#   ansible-playbook -i inventory reset-kafka-with-user.yml -e "confirm_reset=yes"

- name: Reset Kafka Installation (Including User/Group)
  hosts: all
  become: true
  gather_facts: true

  vars:
    kafka_service_name: kafka
    kafka_root_dir: /opt
    kafka_dir: "{{ kafka_root_dir }}/kafka"
    kafka_data_dir: /var/lib/kafka
    kafka_log_dir: /var/log/kafka
    kafka_config_dir: /etc/kafka
    kafka_user: kafka
    kafka_group: kafka
    confirm_reset: "no"

  tasks:
    - name: Safety confirmation
      ansible.builtin.pause:
        prompt: |

          ========================================
          WARNING: DESTRUCTIVE OPERATION!
          ========================================

          This will:
          - Stop and remove Kafka service
          - Delete ALL Kafka data and logs
          - Remove kafka user and group

          Affected directories:
          - {{ kafka_root_dir }}/kafka*
          - {{ kafka_data_dir }}
          - {{ kafka_log_dir }}
          - {{ kafka_config_dir }}

          Press ENTER to continue or Ctrl+C to abort
          ========================================
      when: confirm_reset != "yes"

    - name: Stop Kafka service
      ansible.builtin.service:
        name: "{{ kafka_service_name }}"
        state: stopped
      ignore_errors: true

    - name: Disable Kafka service
      ansible.builtin.service:
        name: "{{ kafka_service_name }}"
        enabled: false
      ignore_errors: true

    - name: Remove systemd service file (RedHat)
      ansible.builtin.file:
        path: /usr/lib/systemd/system/kafka.service
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Remove systemd service file (Debian)
      ansible.builtin.file:
        path: /lib/systemd/system/kafka.service
        state: absent
      when: ansible_os_family == "Debian"

    - name: Remove initd service file (RedHat 6)
      ansible.builtin.file:
        path: /etc/init.d/kafka
        state: absent
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true
      when: ansible_service_mgr == "systemd"

    - name: Find all Kafka directories in /opt
      ansible.builtin.find:
        paths: "{{ kafka_root_dir }}"
        patterns: "kafka*"
        file_type: any
      register: kafka_opt_dirs

    - name: Remove all Kafka directories in /opt
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ kafka_opt_dirs.files }}"
      when: kafka_opt_dirs.files | length > 0

    - name: Remove Kafka data directory
      ansible.builtin.file:
        path: "{{ kafka_data_dir }}"
        state: absent

    - name: Remove Kafka log directory
      ansible.builtin.file:
        path: "{{ kafka_log_dir }}"
        state: absent

    - name: Remove Kafka config directory
      ansible.builtin.file:
        path: "{{ kafka_config_dir }}"
        state: absent

    - name: Remove kafka user
      ansible.builtin.user:
        name: "{{ kafka_user }}"
        state: absent
        remove: true
      ignore_errors: true

    - name: Remove kafka group
      ansible.builtin.group:
        name: "{{ kafka_group }}"
        state: absent
      ignore_errors: true

    - name: Display cleanup summary
      ansible.builtin.debug:
        msg:
          - "Kafka complete reset finished!"
          - "- Service stopped and removed"
          - "- All Kafka files deleted"
          - "- User '{{ kafka_user }}' removed"
          - "- Group '{{ kafka_group }}' removed"
          - ""
          - "The system is now clean and ready for fresh Kafka installation."
