---
- name: Prepare
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: Install Java 17 (OpenJDK) on RedHat/CentOS
      ansible.builtin.yum:
        name: java-17-openjdk
        state: installed
      when: ansible_os_family == "RedHat"

    - name: Install Java 17 (OpenJDK) on Debian
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    # The installation of this package into the container means
    # that the "ps" command is available for viewing the running process.
    - name: Install ps on Debian
      ansible.builtin.apt:
        name: procps
        state: present
      when: ansible_os_family == "Debian"

    - name: Install ps on RedHat/CentOS
      ansible.builtin.yum:
        name: procps
        state: present
      when: ansible_os_family == "RedHat"

    # Format storage for KRaft metadata
    - name: Create metadata directory
      ansible.builtin.file:
        path: /var/lib/kafka/kraft-metadata
        state: directory
        owner: kafka
        group: kafka
        mode: '0755'
      become: yes
      ignore_errors: yes
